/* Generated from web/hamlab.html and web/compact.html. */
#ifndef HAMLAB_WEB_H_
#define HAMLAB_WEB_H_
static const char html[] =
"<!doctype html>\n"
"<html lang=\"de\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>HamLab Powermeter</title>\n"
"<style>body{background:#101820;color:#edf4f8;font:17px system-ui;max-width:920px;margin:auto;padding:20px}header,article{background:#203040;border-radius:14px;padding:20px;margin:15px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}.watts{font-size:64px;color:#77e1bc}small,.note{color:#bfcedb}.meter{position:relative;height:32px;background:#101820;border:1px solid #708596;border-radius:7px;overflow:hidden}.fill{height:100%;width:0;background:#77e1bc;transition:width .1s}.hold{position:absolute;top:0;bottom:0;width:4px;background:#ffd166;transform:translateX(-100%);display:none}.ticks{display:flex;justify-content:space-between;font-size:14px;color:#bfcedb;margin-top:6px}.legend{color:#ffd166}button{background:#31495d;color:#edf4f8;border:1px solid #708596;border-radius:7px;padding:10px;cursor:pointer}a{color:#77e1bc}table{width:100%;text-align:left}td{padding:7px 0}.bad{color:#ffb17b}body.compact .details{display:none}.swr-widget{margin-top:18px}.swr-label{font-size:16px;margin-bottom:6px}.swr-track{position:relative;height:24px;border-radius:6px;overflow:hidden;background:linear-gradient(to right,#359b65 0%,#359b65 25%,#c5a335 25%,#c5a335 50%,#b64848 50%,#b64848 100%)}.swr-marker{position:absolute;top:0;bottom:0;width:4px;background:white;transform:translateX(-100%);display:none}.swr-track.unknown{opacity:.4}.swr-peak{background:#ffd166;width:2px}.swr-help{font-size:12px;color:#bfcedb;margin-top:5px}.swr-track.unknown{opacity:1;background:#59451b}.swr-track.danger{background:repeating-linear-gradient(135deg,#9c222c 0,#9c222c 12px,#651820 12px,#651820 24px)}.swr-warning{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:white;font-size:13px;font-weight:700}.swr-help.warning{font-size:15px;font-weight:650;color:#ffd166}.swr-help.warning.danger{color:#ffb5b5}.swr-label.danger{color:#ffb5b5}.swr-track.quiet{background:#263343}.swr-track.quiet .swr-warning{display:none}.swr-marker.assumed{background:#2196ff;width:6px;transform:translateX(-50%);box-shadow:0 0 3px #111}.assumed-value{color:#64b5ff}</style></head>\n"
"<body><header><h1>HamLab Powermeter</h1><div id=\"status\">Verbinden \u2026</div><small><span id=\"version\"></span> \u00b7 \u00a9 DL2DBG</small></header>\n"
"<article><h2>Vorlaufleistung</h2><div class=\"watts\" id=\"power\">-- W</div><div class=\"meter\" id=\"bar\" role=\"meter\" aria-label=\"Vorlaufleistung\" aria-valuemin=\"0\" aria-valuemax=\"10\"><div class=\"fill\" id=\"fill\"></div><div class=\"hold\" id=\"hold\" title=\"Max-Hold\"></div></div><div class=\"ticks\"><span>0</span><span id=\"tick25\">2,5</span><span id=\"tick50\">5</span><span id=\"tick75\">7,5</span><span id=\"tick100\">10 W</span></div><p>Autoscale: <strong id=\"scale\">10 W</strong> \u00b7 <span class=\"legend\">Gelbe Marke: Max-Hold 3 s</span></p><p>Peak-Hold: <strong id=\"peak\">-- W</strong></p><p id=\"quality\"></p><div class=\"swr-widget\"><div class=\"swr-label\">SWR <strong id=\"swrbarvalue\">--</strong> \u00b7 Max <small id=\"swrbarpeak\">--</small></div><div class=\"swr-track unknown\" id=\"swrtrack\" role=\"meter\" aria-label=\"SWR\" aria-valuemin=\"1\" aria-valuemax=\"3\"><div class=\"swr-warning\" id=\"swrwarning\" style=\"display:none\"></div><div class=\"swr-marker\" id=\"swrmark\"></div><div class=\"swr-marker swr-peak\" id=\"swrhold\"></div></div><div class=\"ticks\"><span>1</span><span>1,5</span><span>2</span><span>2,5</span><span>3+</span></div><div class=\"swr-help\" id=\"swrbarstatus\" role=\"status\">Keine g\u00fcltige SWR-Messung</div></div><p class=\"note\">Vorl\u00e4ufige Kennlinie \u00b7 7,03167 MHz \u00b7 50 \u03a9 \u00b7 gemessen 1,25\u201392,16 W</p><p class=\"note\">HF-Frequenz nicht automatisch gepr\u00fcft. Kennlinie nur bei dieser Frequenz und unver\u00e4ndertem Messaufbau verwenden.</p></article>\n"
"<div class=\"grid\"><article><h2>Vorlauf A0\u2212A3</h2><strong id=\"fv\">-- V</strong><p id=\"fd\" class=\"details\"></p></article><article><h2>R\u00fccklauf A1\u2212A3</h2><strong id=\"rv\">-- V</strong><p id=\"rd\" class=\"details\"></p></article><article><h2>Messkopf A2\u2212A3</h2><strong id=\"cv\">-- V</strong><p id=\"cd\" class=\"details\"></p></article></div>\n"
"<article><h2>R\u00fccklaufleistung / SWR \u00b7 vorl\u00e4ufig</h2><p>R\u00fccklauf: <strong id=\"reversepower\">-- W</strong></p><p>Aktuell: <strong id=\"swr\">--</strong> \u00b7 Peak-Hold: <strong id=\"swrpeak\">--</strong></p><p id=\"swrquality\">Vorl\u00e4ufige R\u00fccklaufkennlinie</p><button id=\"reset\">Peak-Hold zur\u00fccksetzen</button><p id=\"resetstatus\"></p></article>\n"
"<article><h2>A2 \u00b7 Gleichspannungs-Voltmeter</h2><div class=\"watts\" id=\"a2voltage\" style=\"color:#64b5ff\">-- V</div><div class=\"meter\" role=\"meter\" id=\"a2vbar\" aria-label=\"A2 Gleichspannung, direkt am ADC\"><div class=\"fill\" id=\"a2vfill\" style=\"background:#64b5ff\"></div></div><div class=\"ticks\"><span>0 V</span><span id=\"a2vscale\">1 V</span></div><p class=\"note\" id=\"a2vnote\">Direkte Spannungsmessung \u00b7 1:1</p></article>\n"
"<article><h2>A2-Messkopf \u00b7 Leistung an 50 \u03a9</h2><div class=\"watts\" id=\"a2power\" style=\"color:#64b5ff\">--</div><div class=\"meter\" id=\"a2bar\" role=\"meter\" aria-label=\"A2-Messkopf-Leistung\"><div class=\"fill\" id=\"a2fill\" style=\"background:#64b5ff\"></div><div class=\"hold\" id=\"a2hold\"></div></div><div class=\"ticks\"><span>0</span><span id=\"a2tick25\"></span><span id=\"a2tick50\"></span><span id=\"a2tick75\"></span><span id=\"a2tick100\"></span></div><p>Autoscale: <strong id=\"a2scale\">--</strong> \u00b7 <span class=\"legend\">Gelbe Marke: Max-Hold 3 s</span></p><p>Max-Hold: <strong id=\"a2peak\">--</strong></p><p class=\"note\" id=\"a2dbm\">-- dBm</p><p id=\"currentcoupler\" class=\"note\">A2-Messkopf: --</p><p id=\"a2quality\" class=\"note\"></p><button id=\"a2reset\">Hold zur\u00fccksetzen</button></article>\n"
"<p id=\"batteryvoltage\">Akku GP28: --</p>\n"
"<article><h2>Richtkoppler \u00b7 ausgew\u00e4hlte Kennlinien</h2><p class=\"note\">A0/A1 \u00b7 X: Detektorspannung am ADC \u00b7 Y: Leistung in W. Punkte: St\u00fctzstellen; Linien: verwendete Interpolation.</p><div id=\"directionlegend\"></div><svg id=\"directionplot\" viewBox=\"0 0 800 400\" role=\"img\" aria-label=\"Richtkoppler-Kennlinien in Volt und Watt\" style=\"width:100%;height:auto;background:#101820;border-radius:8px\"></svg></article>\n"
"<article><h2>A2-Messkopf \u00b7 ausgew\u00e4hlte Kennlinie</h2><p class=\"note\">Eigene Achsenskalierung \u00b7 Leistung in mW f\u00fcr Kennlinien unter 1 W, sonst in W.</p><div id=\"a2legend\"></div><svg id=\"a2plot\" viewBox=\"0 0 800 400\" role=\"img\" aria-label=\"A2-Messkopf-Kennlinie mit eigener Skalierung\" style=\"width:100%;height:auto;background:#101820;border-radius:8px\"></svg><p id=\"curvestatus\" class=\"note\">Kennlinien werden geladen \u2026</p></article>\n"
"<footer><small id=\"last\">Letzte Messung: --</small><br><a class=\"full-link\" href=\"/\">Vollansicht</a><span class=\"compact-link\"> \u00b7 <a href=\"/compact\">Kompakt A0</a> \u00b7 <a href=\"/compact-a2\">Kompakt A2</a></span></footer>\n"
"<script>\n"
"const el=id=>document.getElementById(id);\n"
"let currentPower=null,heldPower=null;\n"
"function swrNotice(quality){\n"
" const messages={\n"
"  invalid_power_ratio:['SWR NICHT BESTIMMBAR','R\u00fccklauf \u2265 Vorlauf: starke Fehlanpassung oder Messabweichung. Last und Anschluss pr\u00fcfen.','danger'],\n"
"  reverse_above_calibrated_range:['R\u00dcCKLAUF ZU HOCH','SWR nicht bestimmbar: R\u00fccklauf \u00fcber der kalibrierten Messgrenze. Last und Anschluss pr\u00fcfen.','danger'],\n"
"  reverse_below_calibrated_floor:['SWR UNTER MESSGRENZE','R\u00fccklauf unter der Kalibriergrenze. SWR ist nicht bestimmt; dies bedeutet nicht automatisch SWR 1.','caution'],\n"
"  forward_outside_calibrated_range:['SWR NICHT BESTIMMBAR','Vorlauf au\u00dferhalb des Kalibrierbereichs oder kein ausreichendes Signal.','caution'],\n"
"  forward_frequency_not_calibrated:['SWR NICHT KALIBRIERT','F\u00fcr die gew\u00e4hlte R\u00fccklauffrequenz fehlt die passende Vorlaufkalibrierung.','caution'],\n"
"  adc_error:['SWR MESSFEHLER','ADC-Messung ung\u00fcltig oder \u00fcbersteuert.','danger'],\n"
"  offline:['KEINE VERBINDUNG','Keine aktuelle SWR-Messung verf\u00fcgbar.','caution'],\n"
"  reset:['SWR WIRD AKTUALISIERT','Neue Messung abwarten.','caution']\n"
" };\n"
" return messages[quality]||['SWR NICHT BESTIMMBAR','Keine g\u00fcltige SWR-Messung.','caution'];\n"
"}\n"
"function drawSwr(value,peak,quality){\n"
" const valid=Number.isFinite(value)&&value>=1;\n"
" const nearOne=!valid&&quality==='reverse_below_calibrated_floor';\n"
" const held=valid&&Number.isFinite(peak)&&peak>=1;\n"
" const [label,message,severity]=swrNotice(quality);\n"
" const quiet=!valid&&['reverse_below_calibrated_floor','forward_outside_calibrated_range','reset'].includes(quality);\n"
" const danger=valid\?value>=3:severity==='danger';\n"
" el('swrtrack').classList.toggle('danger',danger);\n"
" el('swrwarning').textContent=valid\?(value>3\?'SWR > 3':''):label;\n"
" el('swrwarning').style.display=quiet||(valid&&value<=3)\?'none':'flex';\n"
" el('swrbarstatus').classList.toggle('warning',(!valid&&!quiet)||danger);\n"
" el('swrbarstatus').classList.toggle('danger',danger);\n"
" el('swrbarvalue').textContent=valid\?value.toFixed(2):(nearOne\?'~1':'--');\n"
" el('swrbarpeak').textContent=held\?peak.toFixed(2):'--';\n"
" el('swrtrack').classList.toggle('unknown',!valid&&!nearOne);\n"
" el('swrtrack').classList.toggle('quiet',quiet&&!nearOne);\n"
" el('swrmark').classList.toggle('assumed',nearOne);\n"
" el('swrbarvalue').classList.toggle('assumed-value',nearOne);\n"
" el('swrmark').style.display=valid||nearOne\?'block':'none';\n"
" el('swrmark').style.left=(valid\?Math.max(0.5,Math.min(100,(value-1)*50)):(nearOne\?1:0))+'%';\n"
" el('swrhold').style.display=held\?'block':'none';\n"
" el('swrhold').style.left=(held\?Math.max(0.5,Math.min(100,(peak-1)*50)):0)+'%';\n"
" if(valid)el('swrtrack').setAttribute('aria-valuenow',Math.min(value,3));else el('swrtrack').removeAttribute('aria-valuenow');\n"
" el('swrtrack').setAttribute('aria-valuetext',valid\?'SWR '+value.toFixed(2):(nearOne\?'SWR ungef\u00e4hr 1, angenommen, R\u00fccklauf unter Messgrenze':label+'. '+message));\n"
" el('swrbarstatus').textContent=valid\?(danger\?(value>3\?'SWR > 3 \u2014 Last und Anschluss pr\u00fcfen.':'SWR 3 \u2014 Last und Anschluss pr\u00fcfen.'):'Wei\u00df: gemessen \u00b7 Blau: ~1 angenommen \u00b7 Gelb: Max-Hold 3 s'):(quiet\?(quality==='reverse_below_calibrated_floor'\?'Blau: ~1 angenommen \u00b7 R\u00fccklauf unter Messgrenze; kein gemessener SWR-Wert':'') :message);\n"
"}\n"
"function drawBar(current,peak){\n"
" currentPower=Number.isFinite(current)&&current>=0\?current:null;\n"
" heldPower=Number.isFinite(peak)&&peak>=0\?peak:null;\n"
" const largest=Math.max(currentPower\?\?0,heldPower\?\?0);\n"
" const scale=[10,20,50,100,150].find(v=>largest<=v)\?\?150;\n"
" el('scale').textContent=scale+' W';\n"
" for(const n of [25,50,75,100])el('tick'+n).textContent=(scale*n/100).toLocaleString('de-DE')+(n===100\?' W':'');\n"
" el('fill').style.width=(Math.min(currentPower\?\?0,scale)/scale*100)+'%';\n"
" el('hold').style.display=heldPower===null\?'none':'block';\n"
" el('hold').style.left=(Math.min(heldPower\?\?0,scale)/scale*100)+'%';\n"
" el('hold').title=heldPower===null\?'Max-Hold':'Max-Hold '+heldPower.toFixed(1)+' W';\n"
" el('bar').setAttribute('aria-valuemax',scale);\n"
" if(currentPower===null)el('bar').removeAttribute('aria-valuenow');else el('bar').setAttribute('aria-valuenow',currentPower);\n"
" el('bar').setAttribute('aria-valuetext',currentPower===null\?'Keine aktuelle Messung':currentPower.toFixed(1)+' W, Max-Hold '+(heldPower===null\?'unbekannt':heldPower.toFixed(1)+' W'));\n"
"}\n"
"if(location.pathname.startsWith('/compact'))document.body.classList.add('compact');\n"
"\n"
"function drawA2Voltage(c){\n"
" const overflow=!!(c\?.voltage_overflow||c\?.overrange||(c\?.valid&&Number.isFinite(c.voltage_v)&&c.voltage_v>=3.2));\n"
" const valid=!overflow&&c\?.valid&&!c.overrange&&Number.isFinite(c.input_voltage_v);\n"
" const v=valid\?c.input_voltage_v:null;\n"
" const scale=[0.1,0.2,0.5,1,2,3.3].find(n=>n>=Math.abs(v\?\?0))\?\?3.3;\n"
" el('a2voltage').style.color=overflow\?'#ff6b6b':'#64b5ff';\n"
" el('a2voltage').textContent=overflow\?'OVERFLOW':valid\?v.toLocaleString('de-DE',{minimumFractionDigits:4,maximumFractionDigits:4})+' V':'-- V';\n"
" el('a2vscale').textContent=scale.toLocaleString('de-DE')+' V';\n"
" el('a2vfill').style.background=overflow\?'#e53935':'#64b5ff';\n"
" el('a2vfill').style.width=overflow\?'100%':(Math.max(0,Math.min(v\?\?0,scale))/scale*100)+'%';\n"
" el('a2vbar').setAttribute('aria-valuemin',0);el('a2vbar').setAttribute('aria-valuemax',scale);\n"
" if(valid)el('a2vbar').setAttribute('aria-valuenow',v);else el('a2vbar').removeAttribute('aria-valuenow');\n"
" el('a2vbar').setAttribute('aria-valuetext',overflow\?'Spannungsgrenze: Overflow':valid\?v+' V':'Keine aktuelle Messung');\n"
" el('a2vnote').style.color=overflow\?'#ff6b6b':'';\n"
" el('a2vnote').textContent=overflow\?'Spannungsgrenze / \u00dcbersteuerung \u00b7 ab 3,2 V am ADC \u00b7 Eingangsspannung nicht bestimmbar':valid\?'Gleichspannung direkt am ADC \u00b7 '+c.voltage_v.toFixed(7)+' V \u00d7 '+c.divider_ratio:c\?.overrange\?'ADC \u00fcbersteuert':'Keine aktuelle Spannungsmessung';\n"
"}\n"
"let lastA2=null,lastA2Profile=null;\n"
"function drawA2(data,profile){\n"
" lastA2=data;lastA2Profile=profile;\n"
" const valid=data\?.valid&&Number.isFinite(data.power_50ohm_w);\n"
" const peak=Number.isFinite(data\?.peak_w)\?data.peak_w:null;\n"
" const milli=Number.isFinite(data\?.max_w)&&data.max_w<1;\n"
" const factor=milli\?1000:1,unit=milli\?'mW':'W';\n"
" const value=valid\?data.power_50ohm_w*factor:null,held=peak===null\?null:peak*factor;\n"
" const levels=milli\?[10,20,50,100,150,200,250,500,1000]:[10,20,50,100,150];\n"
" const scale=levels.find(v=>v>=Math.max(value\?\?0,held\?\?0))\?\?levels.at(-1);\n"
" const fmt=v=>v.toLocaleString('de-DE',{maximumFractionDigits:milli\?2:3})+' '+unit;\n"
" el('a2power').textContent=valid\?fmt(value):'-- '+unit;\n"
" el('a2dbm').textContent=valid&&data.power_50ohm_w>0\?(10*Math.log10(data.power_50ohm_w*1000)).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' dBm':'-- dBm';\n"
" el('a2scale').textContent=fmt(scale);\n"
" el('a2peak').textContent=held===null\?'-- '+unit:fmt(held);\n"
" el('a2fill').style.width=(Math.max(0,Math.min(value\?\?0,scale))/scale*100)+'%';\n"
" el('a2hold').style.display=held===null\?'none':'block';\n"
" el('a2hold').style.left=(Math.max(0,Math.min(held\?\?0,scale))/scale*100)+'%';\n"
" for(const n of [25,50,75,100])el('a2tick'+n).textContent=fmt(scale*n/100);\n"
" el('a2bar').setAttribute('aria-valuemin',0);el('a2bar').setAttribute('aria-valuemax',scale);\n"
" if(valid)el('a2bar').setAttribute('aria-valuenow',value);else el('a2bar').removeAttribute('aria-valuenow');\n"
" el('a2bar').setAttribute('aria-valuetext',valid\?fmt(value)+'; Max-Hold '+(held===null\?'--':fmt(held)):'Keine g\u00fcltige A2-Leistung');\n"
" el('currentcoupler').textContent=data\?'Profil '+(profile\?\?'--')+' \u00b7 Referenz '+data.master+' \u00b7 '+(data.calibration_frequency_hz/1e6).toLocaleString('de-DE')+' MHz \u00b7 50 \u03a9':'A2-Messkopf: keine aktuellen Daten';\n"
" el('a2quality').textContent=!data\?'Keine Verbindung':valid\?'Vorl\u00e4ufige Kennlinie \u00b7 Messfrequenz nicht automatisch gepr\u00fcft':data.quality==='outside_calibrated_range'\?'A2 au\u00dferhalb der gemessenen Kennlinie \u00b7 kein g\u00fcltiger Leistungswert':'A2-Messung ung\u00fcltig oder \u00fcbersteuert';\n"
"}\n"
"\n"
"function clear(){drawA2Voltage(null);drawA2(null);el('currentcoupler').textContent='Stromkoppler A2: --';el('batteryvoltage').textContent='Akku GP28: --';drawSwr(null,null,'offline');el('power').textContent='-- W';drawBar(null,heldPower);['swr','reversepower'].forEach(id=>el(id).textContent='--');['fv','rv','cv'].forEach(id=>el(id).textContent='-- V');['fd','rd','cd'].forEach(id=>el(id).textContent='');}\n"
"async function poll(){const started=performance.now();try{const res=await fetch('/api/v1/state',{cache:'no-store',signal:AbortSignal.timeout(4000)});const x=await res.json();\n"
"if(!res.ok||!x.measurement_valid){clear();el('status').textContent='Messfehler '+x.measurement_error;el('quality').textContent='Keine g\u00fcltige Messung';}\n"
"else{const clock=x.time;\n"
"if(clock&&Number.isFinite(clock.last_measurement_unix_ms)) {\n"
" const d=new Date(clock.last_measurement_unix_ms);\n"
" el('last').textContent='Letzte Messung: '+d.toLocaleString('de-DE',{timeZone:'Europe/Berlin'})+' \u00b7 '+clock.last_forward_w.toFixed(1)+' W \u00b7 SWR '+(Number.isFinite(clock.last_swr)\?clock.last_swr.toFixed(2):'--')+' \u00b7 '+(clock.synced\?'NTP':'NTP derzeit nicht synchronisiert');\n"
" el('last').title=d.toISOString()+' (UTC)';\n"
"} else {el('last').textContent=clock&&clock.synced\?'NTP synchronisiert \u00b7 noch keine g\u00fcltige Leistungsmessung':'Letzte Messung: -- \u00b7 warte auf NTP';}\n"
"el('status').textContent='Verbunden \u00b7 '+new Date().toLocaleTimeString('de-DE');\n"
"x.channels.slice(0,3).forEach((c,i)=>{el(['fv','rv','cv'][i]).textContent=c.valid&&Number.isFinite(c.voltage_v)\?c.voltage_v.toFixed(6)+' V':'ADC-Fehler';el(['fd','rd','cd'][i]).textContent='Raw '+c.raw+' \u00b7 Bereich \u00b1'+c.range_mv+' mV \u00b7 AutoRange'+(c.overrange\?' \u00b7 \u00dcbersteuerung':'');});\n"
"const cc=x.current_coupler,ic=x.channels.find(c=>c.role==='current');\n"
"\n"
"el('batteryvoltage').textContent='Akku GP28: '+(x.battery\?.valid\?x.battery.voltage_v.toFixed(2)+' V':'-- V');\n"
"const p=x.power;const valid=p.forward_valid&&Number.isFinite(p.forward_w);el('power').textContent=valid\?p.forward_w.toFixed(1)+' W':'-- W';drawBar(valid\?p.forward_w:null,p.peak_w);el('quality').textContent=valid\?'Vorl\u00e4ufig kalibriert':p.quality==='outside_calibrated_range'\?'Unter-/oberhalb der kalibrierten Kennlinie \u00b7 Rohspannung weiterhin sichtbar':'ADC-Fehler';el('peak').textContent=Number.isFinite(p.peak_w)\?p.peak_w.toFixed(1)+' W':'-- W';\n"
"const swr=x.swr;drawSwr(swr.valid\?swr.value:null,swr.peak,swr.quality);el('reversepower').textContent=Number.isFinite(p.reverse_w)\?p.reverse_w.toFixed(3)+' W':'-- W';el('swrquality').textContent=swr.valid\?'Vorl\u00e4ufige R\u00fccklaufkennlinie \u00b7 umgedrehter Koppler':(swr.quality==='reverse_below_calibrated_floor'\?'~1 angenommen \u00b7 kein gemessener SWR-Wert':swrNotice(swr.quality)[1]);el('swr').textContent=swr.enabled&&Number.isFinite(swr.value)\?swr.value.toFixed(2):(swr.quality==='reverse_below_calibrated_floor'\?'~1':'--');el('swrpeak').textContent=swr.enabled&&Number.isFinite(swr.peak)\?swr.peak.toFixed(2):'--';}drawA2Voltage(x.channels\?.find(c=>c.input==='A2-A3'));drawA2(x.current_coupler,x.curve_profiles\?.current);}\n"
"catch(e){clear();el('status').textContent='Verbindung unterbrochen';el('quality').textContent='Keine aktuelle Messung';}setTimeout(poll,Math.max(20,200-(performance.now()-started)));}\n"
"el('reset').onclick=async()=>{el('reset').disabled=true;try{const r=await fetch('/api/v1/peak/reset',{method:'POST',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error();el('peak').textContent='-- W';el('swrpeak').textContent='--';drawBar(currentPower,null);if(lastA2)drawA2({...lastA2,peak_w:null},lastA2Profile);drawSwr(null,null,'reset');el('resetstatus').textContent='Peak-Hold zur\u00fcckgesetzt';}catch(e){el('resetstatus').textContent='Zur\u00fccksetzen fehlgeschlagen';}finally{el('reset').disabled=false;}};\n"
"el('a2reset').onclick=()=>el('reset').click();\n"
"fetch('/api/v1/info').then(r=>r.json()).then(x=>el('version').textContent='Firmware '+x.version).catch(()=>{});poll();\n"
"\n"
"const curveColors=['#77e1bc','#ffb17b','#bda0ff','#64b5ff'];\n"
"const curveLabels=['Vorlauf A0','R\u00fccklauf 7,1 MHz A1','R\u00fccklauf 50,1 MHz A1','A2-Messkopf'];\n"
"const visibleCurves=new Set(['forward','reverse_7mhz','reverse_50mhz','current']);\n"
"let curveData=null;\n"
"function niceLimit(value){\n"
" if(!(value>0))return 1;\n"
" const base=10**Math.floor(Math.log10(value));\n"
" return ([1,2,2.5,5,10].find(v=>v*base>=value)||10)*base;\n"
"}\n"
"function drawCurveGroup(plotId,group,milli){\n"
" const shown=group.filter(c=>visibleCurves.has(c.id));\n"
" const factor=milli\?1000:1,unit=milli\?'mW':'W';\n"
" const xmax=niceLimit(Math.max(0.001,...shown.flatMap(c=>c.points.map(p=>p[0])))*1.02);\n"
" const ymax=niceLimit(Math.max(milli\?0.001:0.01,...shown.flatMap(c=>c.points.map(p=>p[1]*factor)))*1.02);\n"
" const svg=el(plotId);svg.replaceChildren();\n"
" const add=(tag,attrs,text)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;svg.append(n);return n;};\n"
" const fmt=v=>v.toLocaleString('de-DE',{maximumFractionDigits:5});\n"
" const x=v=>65+v/xmax*710,y=w=>345-w*factor/ymax*310;\n"
" svg.setAttribute('aria-label',(plotId==='a2plot'\?'A2-Messkopf':'Richtkoppler')+' \u00b7 Spannung in V, Leistung in '+unit);\n"
" for(let i=0;i<=5;i++){\n"
"  const xx=65+i*142,yy=345-i*62;\n"
"  add('line',{x1:xx,y1:35,x2:xx,y2:345,stroke:'#31495d'});\n"
"  add('line',{x1:65,y1:yy,x2:775,y2:yy,stroke:'#31495d'});\n"
"  add('text',{x:xx,y:368,fill:'#bfcedb','text-anchor':'middle','font-size':13},fmt(xmax*i/5));\n"
"  add('text',{x:55,y:yy+4,fill:'#bfcedb','text-anchor':'end','font-size':13},fmt(ymax*i/5));\n"
" }\n"
" add('text',{x:65,y:22,fill:'#edf4f8','font-size':14},'Leistung / '+unit);\n"
" add('text',{x:775,y:393,fill:'#edf4f8','text-anchor':'end','font-size':14},'Detektorspannung / V');\n"
" shown.forEach(c=>{\n"
"  const i=curveData.curves.findIndex(v=>v.id===c.id);\n"
"  add('polyline',{points:c.points.map(p=>x(p[0])+','+y(p[1])).join(' '),fill:'none',stroke:curveColors[i],'stroke-width':2});\n"
"  c.points.forEach(p=>{const n=add('circle',{cx:x(p[0]),cy:y(p[1]),r:3,fill:curveColors[i]});const t=document.createElementNS('http://www.w3.org/2000/svg','title');t.textContent=fmt(p[0])+' V \u2192 '+fmt(p[1]*factor)+' '+unit;n.append(t);});\n"
" });\n"
" if(!shown.length)add('text',{x:420,y:180,fill:'#bfcedb','text-anchor':'middle'},'Keine Kurve eingeblendet');\n"
"}\n"
"function drawCurves(){\n"
" if(!curveData)return;\n"
" const a2=curveData.curves.filter(c=>c.id==='current');\n"
" const milli=a2.length>0&&Math.max(...a2.flatMap(c=>c.points.map(p=>p[1])))<1;\n"
" drawCurveGroup('directionplot',curveData.curves.filter(c=>c.id!=='current'),false);\n"
" drawCurveGroup('a2plot',a2,milli);\n"
"}\n"
"async function loadCurves(){\n"
" try{const r=await fetch('/api/v1/curves',{cache:'no-store',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data.curves)||data.curves.length!==4)throw Error();curveData=data;\n"
"  el('directionlegend').replaceChildren();el('a2legend').replaceChildren();\n"
"  data.curves.forEach((c,i)=>{const label=document.createElement('label');label.style.cssText='display:block;margin:8px 0;color:'+curveColors[i];const check=document.createElement('input');check.type='checkbox';check.checked=visibleCurves.has(c.id);check.onchange=()=>{if(check.checked)visibleCurves.add(c.id);else visibleCurves.delete(c.id);drawCurves();};label.append(check,document.createTextNode(' '+curveLabels[i]+' \u00b7 '+data.profiles[c.id]+' \u00b7 '+(c.frequency_hz/1e6).toFixed(5)+' MHz'));el(c.id==='current'\?'a2legend':'directionlegend').append(label);});\n"
"  drawCurves();el('curvestatus').textContent='Aktiver Satz \u00b7 aktualisiert '+new Date().toLocaleTimeString('de-DE')+' \u00b7 Kurven einzeln ein-/ausblenden; Punkte zeigen V/W beim Dar\u00fcberfahren.';\n"
" }catch(e){el('curvestatus').textContent='Kennlinien derzeit nicht abrufbar \u00b7 eventuell l\u00e4uft ein Import. Diagramm zeigt den zuletzt geladenen Satz.';}\n"
" setTimeout(loadCurves,5000);\n"
"}\n"
"loadCurves();\n"
"</script></body></html>\n"
;
static const char compact_html[] =
"<!doctype html>\n"
"<html lang=\"de\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>HamLab Powermeter</title>\n"
"<style>body{background:#101820;color:#edf4f8;font:17px system-ui;max-width:920px;margin:auto;padding:20px}header,article{background:#203040;border-radius:14px;padding:20px;margin:15px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}.watts{font-size:64px;color:#77e1bc}small,.note{color:#bfcedb}.meter{position:relative;height:32px;background:#101820;border:1px solid #708596;border-radius:7px;overflow:hidden}.fill{height:100%;width:0;background:#77e1bc;transition:width .1s}.hold{position:absolute;top:0;bottom:0;width:4px;background:#ffd166;transform:translateX(-100%);display:none}.ticks{display:flex;justify-content:space-between;font-size:14px;color:#bfcedb;margin-top:6px}.legend{color:#ffd166}button{background:#31495d;color:#edf4f8;border:1px solid #708596;border-radius:7px;padding:10px;cursor:pointer}a{color:#77e1bc}table{width:100%;text-align:left}td{padding:7px 0}.bad{color:#ffb17b}body.compact{max-width:560px;padding:12px}body.compact .grid,body.compact article:not(:first-of-type),body.compact> a,body.compact .note,body.compact #quality,body.compact article>h2,body.compact article>p{display:none}body.compact article{margin:0;padding:16px}body.compact .watts{font-size:56px;line-height:1.2;margin-bottom:12px}body.compact .ticks{font-size:13px}body.compact .meter{cursor:pointer}body.compact header{background:none;padding:0;margin:0 0 8px}body.compact h1{font-size:16px;font-weight:500;margin:0}body.compact header small{font-size:11px;color:#bfcedb}body.compact #status{font-size:12px;color:#bfcedb;margin-top:4px}footer{margin-top:10px;font-size:13px;line-height:1.7}body.compact .compact-link{display:none}body.compact article>p.peak-label{display:block;font-size:13px;margin:8px 0 0;color:#ffd166}.swr-widget{margin-top:18px}.swr-label{font-size:16px;margin-bottom:6px}.swr-track{position:relative;height:24px;border-radius:6px;overflow:hidden;background:linear-gradient(to right,#359b65 0%,#359b65 25%,#c5a335 25%,#c5a335 50%,#b64848 50%,#b64848 100%)}.swr-marker{position:absolute;top:0;bottom:0;width:4px;background:white;transform:translateX(-100%);display:none}.swr-track.unknown{opacity:.4}.swr-peak{background:#ffd166;width:2px}.swr-help{font-size:12px;color:#bfcedb;margin-top:5px}.swr-track.unknown{opacity:1;background:#59451b}.swr-track.danger{background:repeating-linear-gradient(135deg,#9c222c 0,#9c222c 12px,#651820 12px,#651820 24px)}.swr-warning{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:white;font-size:13px;font-weight:700}.swr-help.warning{font-size:15px;font-weight:650;color:#ffd166}.swr-help.warning.danger{color:#ffb5b5}.swr-label.danger{color:#ffb5b5}.swr-track.quiet{background:#263343}.swr-track.quiet .swr-warning{display:none}.swr-marker.assumed{background:#2196ff;width:6px;transform:translateX(-50%);box-shadow:0 0 3px #111}.assumed-value{color:#64b5ff}</style></head>\n"
"<body><header><h1>HamLab Powermeter</h1><div id=\"status\">Verbinden \u2026</div><small><span id=\"version\"></span> \u00b7 \u00a9 DL2DBG</small></header>\n"
"<article><h2>Vorlaufleistung</h2><div class=\"watts\" id=\"power\">-- W</div><div class=\"meter\" id=\"bar\" role=\"meter\" aria-label=\"Vorlaufleistung\" title=\"Doppelklick: Max-Hold zur\u00fccksetzen\" aria-valuemin=\"0\" aria-valuemax=\"10\"><div class=\"fill\" id=\"fill\"></div><div class=\"hold\" id=\"hold\" title=\"Max-Hold\"></div></div><div class=\"ticks\"><span>0</span><span id=\"tick25\">2,5</span><span id=\"tick50\">5</span><span id=\"tick75\">7,5</span><span id=\"tick100\">10 W</span></div><p>Autoscale: <strong id=\"scale\">10 W</strong> \u00b7 <span class=\"legend\">Gelbe Marke: Max-Hold 3 s</span></p><p class=\"peak-label\">Max-Hold: <strong id=\"peak\">-- W</strong></p><p id=\"quality\"></p><div class=\"swr-widget\"><div class=\"swr-label\">SWR <strong id=\"swrbarvalue\">--</strong> \u00b7 Max <small id=\"swrbarpeak\">--</small></div><div class=\"swr-track unknown\" id=\"swrtrack\" role=\"meter\" aria-label=\"SWR\" aria-valuemin=\"1\" aria-valuemax=\"3\"><div class=\"swr-warning\" id=\"swrwarning\" style=\"display:none\"></div><div class=\"swr-marker\" id=\"swrmark\"></div><div class=\"swr-marker swr-peak\" id=\"swrhold\"></div></div><div class=\"ticks\"><span>1</span><span>1,5</span><span>2</span><span>2,5</span><span>3+</span></div><div class=\"swr-help\" id=\"swrbarstatus\" role=\"status\">Keine g\u00fcltige SWR-Messung</div></div><p class=\"note\">Vorl\u00e4ufige Kennlinie \u00b7 7,03167 MHz \u00b7 50 \u03a9 \u00b7 gemessen 1,25\u201392,16 W</p><p class=\"note\">HF-Frequenz nicht automatisch gepr\u00fcft. Kennlinie nur bei dieser Frequenz und unver\u00e4ndertem Messaufbau verwenden.</p></article>\n"
"<div class=\"grid\"><article><h2>Vorlauf A0\u2212A3</h2><strong id=\"fv\">-- V</strong><p id=\"fd\" class=\"details\"></p></article><article><h2>R\u00fccklauf A1\u2212A3</h2><strong id=\"rv\">-- V</strong><p id=\"rd\" class=\"details\"></p></article></div>\n"
"<article><h2>R\u00fccklaufleistung / SWR \u00b7 vorl\u00e4ufig</h2><p>R\u00fccklauf: <strong id=\"reversepower\">-- W</strong></p><p>Aktuell: <strong id=\"swr\">--</strong> \u00b7 Peak-Hold: <strong id=\"swrpeak\">--</strong></p><p id=\"swrquality\">Vorl\u00e4ufige R\u00fccklaufkennlinie</p><button id=\"reset\">Peak-Hold zur\u00fccksetzen</button><p id=\"resetstatus\"></p></article><footer><small id=\"last\">Letzte Messung: --</small><br><a class=\"full-link\" href=\"/\">Vollansicht</a><span class=\"compact-link\"> \u00b7 <a href=\"/compact\">Kompaktansicht</a></span> \u00b7 <a href=\"/compact-a2\">Kompakt A2</a></footer>\n"
"<script>\n"
"const el=id=>document.getElementById(id);\n"
"let currentPower=null,heldPower=null;\n"
"function swrNotice(quality){\n"
" const messages={\n"
"  invalid_power_ratio:['SWR NICHT BESTIMMBAR','R\u00fccklauf \u2265 Vorlauf: starke Fehlanpassung oder Messabweichung. Last und Anschluss pr\u00fcfen.','danger'],\n"
"  reverse_above_calibrated_range:['R\u00dcCKLAUF ZU HOCH','SWR nicht bestimmbar: R\u00fccklauf \u00fcber der kalibrierten Messgrenze. Last und Anschluss pr\u00fcfen.','danger'],\n"
"  reverse_below_calibrated_floor:['SWR UNTER MESSGRENZE','R\u00fccklauf unter der Kalibriergrenze. SWR ist nicht bestimmt; dies bedeutet nicht automatisch SWR 1.','caution'],\n"
"  forward_outside_calibrated_range:['SWR NICHT BESTIMMBAR','Vorlauf au\u00dferhalb des Kalibrierbereichs oder kein ausreichendes Signal.','caution'],\n"
"  forward_frequency_not_calibrated:['SWR NICHT KALIBRIERT','F\u00fcr die gew\u00e4hlte R\u00fccklauffrequenz fehlt die passende Vorlaufkalibrierung.','caution'],\n"
"  adc_error:['SWR MESSFEHLER','ADC-Messung ung\u00fcltig oder \u00fcbersteuert.','danger'],\n"
"  offline:['KEINE VERBINDUNG','Keine aktuelle SWR-Messung verf\u00fcgbar.','caution'],\n"
"  reset:['SWR WIRD AKTUALISIERT','Neue Messung abwarten.','caution']\n"
" };\n"
" return messages[quality]||['SWR NICHT BESTIMMBAR','Keine g\u00fcltige SWR-Messung.','caution'];\n"
"}\n"
"function drawSwr(value,peak,quality){\n"
" const valid=Number.isFinite(value)&&value>=1;\n"
" const nearOne=!valid&&quality==='reverse_below_calibrated_floor';\n"
" const held=valid&&Number.isFinite(peak)&&peak>=1;\n"
" const [label,message,severity]=swrNotice(quality);\n"
" const quiet=!valid&&['reverse_below_calibrated_floor','forward_outside_calibrated_range','reset'].includes(quality);\n"
" const danger=valid\?value>=3:severity==='danger';\n"
" el('swrtrack').classList.toggle('danger',danger);\n"
" el('swrwarning').textContent=valid\?(value>3\?'SWR > 3':''):label;\n"
" el('swrwarning').style.display=quiet||(valid&&value<=3)\?'none':'flex';\n"
" el('swrbarstatus').classList.toggle('warning',(!valid&&!quiet)||danger);\n"
" el('swrbarstatus').classList.toggle('danger',danger);\n"
" el('swrbarvalue').textContent=valid\?value.toFixed(2):(nearOne\?'~1':'--');\n"
" el('swrbarpeak').textContent=held\?peak.toFixed(2):'--';\n"
" el('swrtrack').classList.toggle('unknown',!valid&&!nearOne);\n"
" el('swrtrack').classList.toggle('quiet',quiet&&!nearOne);\n"
" el('swrmark').classList.toggle('assumed',nearOne);\n"
" el('swrbarvalue').classList.toggle('assumed-value',nearOne);\n"
" el('swrmark').style.display=valid||nearOne\?'block':'none';\n"
" el('swrmark').style.left=(valid\?Math.max(0.5,Math.min(100,(value-1)*50)):(nearOne\?1:0))+'%';\n"
" el('swrhold').style.display=held\?'block':'none';\n"
" el('swrhold').style.left=(held\?Math.max(0.5,Math.min(100,(peak-1)*50)):0)+'%';\n"
" if(valid)el('swrtrack').setAttribute('aria-valuenow',Math.min(value,3));else el('swrtrack').removeAttribute('aria-valuenow');\n"
" el('swrtrack').setAttribute('aria-valuetext',valid\?'SWR '+value.toFixed(2):(nearOne\?'SWR ungef\u00e4hr 1, angenommen, R\u00fccklauf unter Messgrenze':label+'. '+message));\n"
" el('swrbarstatus').textContent=valid\?(danger\?(value>3\?'SWR > 3 \u2014 Last und Anschluss pr\u00fcfen.':'SWR 3 \u2014 Last und Anschluss pr\u00fcfen.'):'Wei\u00df: gemessen \u00b7 Blau: ~1 angenommen \u00b7 Gelb: Max-Hold 3 s'):(quiet\?(quality==='reverse_below_calibrated_floor'\?'Blau: ~1 angenommen \u00b7 R\u00fccklauf unter Messgrenze; kein gemessener SWR-Wert':'') :message);\n"
"}\n"
"function drawBar(current,peak){\n"
" currentPower=Number.isFinite(current)&&current>=0\?current:null;\n"
" heldPower=Number.isFinite(peak)&&peak>=0\?peak:null;\n"
" const largest=Math.max(currentPower\?\?0,heldPower\?\?0);\n"
" const scale=[10,20,50,100,150].find(v=>largest<=v)\?\?150;\n"
" el('scale').textContent=scale+' W';\n"
" for(const n of [25,50,75,100])el('tick'+n).textContent=(scale*n/100).toLocaleString('de-DE')+(n===100\?' W':'');\n"
" el('fill').style.width=(Math.min(currentPower\?\?0,scale)/scale*100)+'%';\n"
" el('hold').style.display=heldPower===null\?'none':'block';\n"
" el('hold').style.left=(Math.min(heldPower\?\?0,scale)/scale*100)+'%';\n"
" el('hold').title=heldPower===null\?'Max-Hold':'Max-Hold '+heldPower.toFixed(1)+' W';\n"
" el('bar').setAttribute('aria-valuemax',scale);\n"
" if(currentPower===null)el('bar').removeAttribute('aria-valuenow');else el('bar').setAttribute('aria-valuenow',currentPower);\n"
" el('bar').setAttribute('aria-valuetext',currentPower===null\?'Keine aktuelle Messung':currentPower.toFixed(1)+' W, Max-Hold '+(heldPower===null\?'unbekannt':heldPower.toFixed(1)+' W'));\n"
"}\n"
"if(location.pathname.startsWith('/compact'))document.body.classList.add('compact');\n"
"function clear(){drawSwr(null,null,'offline');el('power').textContent='-- W';drawBar(null,heldPower);['swr','reversepower'].forEach(id=>el(id).textContent='--');['fv','rv'].forEach(id=>el(id).textContent='-- V');['fd','rd'].forEach(id=>el(id).textContent='');}\n"
"async function poll(){const started=performance.now();try{const res=await fetch('/api/v1/state',{cache:'no-store',signal:AbortSignal.timeout(4000)});const x=await res.json();\n"
"if(!res.ok||!x.measurement_valid){clear();el('status').textContent='Messfehler '+x.measurement_error;el('quality').textContent='Keine g\u00fcltige Messung';}\n"
"else{const clock=x.time;\n"
"if(clock&&Number.isFinite(clock.last_measurement_unix_ms)) {\n"
" const d=new Date(clock.last_measurement_unix_ms);\n"
" el('last').textContent='Letzte Messung: '+d.toLocaleString('de-DE',{timeZone:'Europe/Berlin'})+' \u00b7 '+clock.last_forward_w.toFixed(1)+' W \u00b7 SWR '+(Number.isFinite(clock.last_swr)\?clock.last_swr.toFixed(2):'--')+' \u00b7 '+(clock.synced\?'NTP':'NTP derzeit nicht synchronisiert');\n"
" el('last').title=d.toISOString()+' (UTC)';\n"
"} else {el('last').textContent=clock&&clock.synced\?'NTP synchronisiert \u00b7 noch keine g\u00fcltige Leistungsmessung':'Letzte Messung: -- \u00b7 warte auf NTP';}\n"
"el('status').textContent='Verbunden \u00b7 '+new Date().toLocaleTimeString('de-DE');\n"
"x.channels.forEach((c,i)=>{el(i\?'rv':'fv').textContent=c.valid&&Number.isFinite(c.voltage_v)\?c.voltage_v.toFixed(6)+' V':'ADC-Fehler';el(i\?'rd':'fd').textContent='Raw '+c.raw+' \u00b7 Bereich \u00b1'+c.range_mv+' mV \u00b7 AutoRange'+(c.overrange\?' \u00b7 \u00dcbersteuerung':'');});\n"
"const p=x.power;const valid=p.forward_valid&&Number.isFinite(p.forward_w);el('power').textContent=valid\?p.forward_w.toFixed(1)+' W':'-- W';drawBar(valid\?p.forward_w:null,p.peak_w);el('quality').textContent=valid\?'Vorl\u00e4ufig kalibriert':p.quality==='outside_calibrated_range'\?'Unter-/oberhalb der kalibrierten Kennlinie \u00b7 Rohspannung weiterhin sichtbar':'ADC-Fehler';el('peak').textContent=Number.isFinite(p.peak_w)\?p.peak_w.toFixed(1)+' W':'-- W';\n"
"const swr=x.swr;drawSwr(swr.valid\?swr.value:null,swr.peak,swr.quality);el('reversepower').textContent=Number.isFinite(p.reverse_w)\?p.reverse_w.toFixed(3)+' W':'-- W';el('swrquality').textContent=swr.valid\?'Vorl\u00e4ufige R\u00fccklaufkennlinie \u00b7 umgedrehter Koppler':(swr.quality==='reverse_below_calibrated_floor'\?'~1 angenommen \u00b7 kein gemessener SWR-Wert':swrNotice(swr.quality)[1]);el('swr').textContent=swr.enabled&&Number.isFinite(swr.value)\?swr.value.toFixed(2):(swr.quality==='reverse_below_calibrated_floor'\?'~1':'--');el('swrpeak').textContent=swr.enabled&&Number.isFinite(swr.peak)\?swr.peak.toFixed(2):'--';}}\n"
"catch(e){clear();el('status').textContent='Verbindung unterbrochen';el('quality').textContent='Keine aktuelle Messung';}setTimeout(poll,Math.max(20,200-(performance.now()-started)));}\n"
"el('reset').onclick=async()=>{el('reset').disabled=true;try{const r=await fetch('/api/v1/peak/reset',{method:'POST',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error();el('peak').textContent='-- W';el('swrpeak').textContent='--';drawBar(currentPower,null);drawSwr(null,null,'reset');el('resetstatus').textContent='Peak-Hold zur\u00fcckgesetzt';}catch(e){el('resetstatus').textContent='Zur\u00fccksetzen fehlgeschlagen';}finally{el('reset').disabled=false;}};\n"
"el('bar').ondblclick=()=>el('reset').click();\n"
"fetch('/api/v1/info').then(r=>r.json()).then(x=>el('version').textContent='Firmware '+x.version).catch(()=>{});poll();\n"
"</script></body></html>\n"
;
static const char compact_a2_html[] =
"<!doctype html>\n"
"<html lang=\"de\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>HamLab A2 kompakt</title>\n"
"<style>body{background:#101820;color:#edf4f8;font:16px system-ui;max-width:560px;margin:auto;padding:12px}h1{font-size:16px;font-weight:500;margin:0}header{margin-bottom:10px}small,#status,.note{font-size:12px;color:#bfcedb}article{background:#203040;border-radius:14px;padding:16px}article h2,article>p:not(.note),#a2reset{display:none}.watts{font-size:56px;line-height:1.2;margin-bottom:12px}.meter{position:relative;height:32px;background:#101820;border:1px solid #708596;border-radius:7px;overflow:hidden;cursor:pointer}.fill{height:100%;width:0;transition:width .1s}.hold{position:absolute;top:0;bottom:0;width:4px;background:#ffd166;transform:translateX(-100%);display:none}.ticks{display:flex;justify-content:space-between;font-size:12px;color:#bfcedb;margin-top:6px}.note{margin:8px 0 0}article>p.a2-peak{display:block;font-size:13px;color:#ffd166;margin:8px 0 0}footer{font-size:12px;margin-top:12px}a{color:#77e1bc}</style></head>\n"
"<body><header><h1>HamLab \u00b7 A2-Messkopf</h1><small><span id=\"version\"></span> \u00b7 \u00a9 DL2DBG</small><div id=\"status\">Verbinden \u2026</div></header>\n"
"<article><h2>A2 \u00b7 Gleichspannungs-Voltmeter</h2><div class=\"watts\" id=\"a2voltage\" style=\"color:#64b5ff\">-- V</div><div class=\"meter\" role=\"meter\" id=\"a2vbar\" aria-label=\"A2 Gleichspannung, direkt am ADC\"><div class=\"fill\" id=\"a2vfill\" style=\"background:#64b5ff\"></div></div><div class=\"ticks\"><span>0 V</span><span id=\"a2vscale\">1 V</span></div><p class=\"note\" id=\"a2vnote\">Direkte Spannungsmessung \u00b7 1:1</p></article>\n"
"<article><h2>A2-Messkopf \u00b7 Leistung an 50 \u03a9</h2><div class=\"watts\" id=\"a2power\" style=\"color:#64b5ff\">--</div><div class=\"meter\" id=\"a2bar\" role=\"meter\" aria-label=\"A2-Messkopf-Leistung\"><div class=\"fill\" id=\"a2fill\" style=\"background:#64b5ff\"></div><div class=\"hold\" id=\"a2hold\"></div></div><div class=\"ticks\"><span>0</span><span id=\"a2tick25\"></span><span id=\"a2tick50\"></span><span id=\"a2tick75\"></span><span id=\"a2tick100\"></span></div><p>Autoscale: <strong id=\"a2scale\">--</strong> \u00b7 <span class=\"legend\">Gelbe Marke: Max-Hold 3 s</span></p><p class=\"a2-peak\">Max-Hold: <strong id=\"a2peak\">--</strong></p><p class=\"note\" id=\"a2dbm\">-- dBm</p><p id=\"currentcoupler\" class=\"note\">A2-Messkopf: --</p><p id=\"a2quality\" class=\"note\"></p><button id=\"a2reset\">Hold zur\u00fccksetzen</button></article>\n"
"<footer><a href=\"/\">Vollansicht</a> \u00b7 <a href=\"/compact\">Kompakt A0</a></footer>\n"
"<script>\n"
"const el=id=>document.getElementById(id);\n"
"function drawA2Voltage(c){\n"
" const overflow=!!(c\?.voltage_overflow||c\?.overrange||(c\?.valid&&Number.isFinite(c.voltage_v)&&c.voltage_v>=3.2));\n"
" const valid=!overflow&&c\?.valid&&!c.overrange&&Number.isFinite(c.input_voltage_v);\n"
" const v=valid\?c.input_voltage_v:null;\n"
" const scale=[0.1,0.2,0.5,1,2,3.3].find(n=>n>=Math.abs(v\?\?0))\?\?3.3;\n"
" el('a2voltage').style.color=overflow\?'#ff6b6b':'#64b5ff';\n"
" el('a2voltage').textContent=overflow\?'OVERFLOW':valid\?v.toLocaleString('de-DE',{minimumFractionDigits:4,maximumFractionDigits:4})+' V':'-- V';\n"
" el('a2vscale').textContent=scale.toLocaleString('de-DE')+' V';\n"
" el('a2vfill').style.background=overflow\?'#e53935':'#64b5ff';\n"
" el('a2vfill').style.width=overflow\?'100%':(Math.max(0,Math.min(v\?\?0,scale))/scale*100)+'%';\n"
" el('a2vbar').setAttribute('aria-valuemin',0);el('a2vbar').setAttribute('aria-valuemax',scale);\n"
" if(valid)el('a2vbar').setAttribute('aria-valuenow',v);else el('a2vbar').removeAttribute('aria-valuenow');\n"
" el('a2vbar').setAttribute('aria-valuetext',overflow\?'Spannungsgrenze: Overflow':valid\?v+' V':'Keine aktuelle Messung');\n"
" el('a2vnote').style.color=overflow\?'#ff6b6b':'';\n"
" el('a2vnote').textContent=overflow\?'Spannungsgrenze / \u00dcbersteuerung \u00b7 ab 3,2 V am ADC \u00b7 Eingangsspannung nicht bestimmbar':valid\?'Gleichspannung direkt am ADC \u00b7 '+c.voltage_v.toFixed(7)+' V \u00d7 '+c.divider_ratio:c\?.overrange\?'ADC \u00fcbersteuert':'Keine aktuelle Spannungsmessung';\n"
"}\n"
"let lastA2=null,lastA2Profile=null;\n"
"function drawA2(data,profile){\n"
" lastA2=data;lastA2Profile=profile;\n"
" const valid=data\?.valid&&Number.isFinite(data.power_50ohm_w);\n"
" const peak=Number.isFinite(data\?.peak_w)\?data.peak_w:null;\n"
" const milli=Number.isFinite(data\?.max_w)&&data.max_w<1;\n"
" const factor=milli\?1000:1,unit=milli\?'mW':'W';\n"
" const value=valid\?data.power_50ohm_w*factor:null,held=peak===null\?null:peak*factor;\n"
" const levels=milli\?[10,20,50,100,150,200,250,500,1000]:[10,20,50,100,150];\n"
" const scale=levels.find(v=>v>=Math.max(value\?\?0,held\?\?0))\?\?levels.at(-1);\n"
" const fmt=v=>v.toLocaleString('de-DE',{maximumFractionDigits:milli\?2:3})+' '+unit;\n"
" el('a2power').textContent=valid\?fmt(value):'-- '+unit;\n"
" el('a2dbm').textContent=valid&&data.power_50ohm_w>0\?(10*Math.log10(data.power_50ohm_w*1000)).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' dBm':'-- dBm';\n"
" el('a2scale').textContent=fmt(scale);\n"
" el('a2peak').textContent=held===null\?'-- '+unit:fmt(held);\n"
" el('a2fill').style.width=(Math.max(0,Math.min(value\?\?0,scale))/scale*100)+'%';\n"
" el('a2hold').style.display=held===null\?'none':'block';\n"
" el('a2hold').style.left=(Math.max(0,Math.min(held\?\?0,scale))/scale*100)+'%';\n"
" for(const n of [25,50,75,100])el('a2tick'+n).textContent=fmt(scale*n/100);\n"
" el('a2bar').setAttribute('aria-valuemin',0);el('a2bar').setAttribute('aria-valuemax',scale);\n"
" if(valid)el('a2bar').setAttribute('aria-valuenow',value);else el('a2bar').removeAttribute('aria-valuenow');\n"
" el('a2bar').setAttribute('aria-valuetext',valid\?fmt(value)+'; Max-Hold '+(held===null\?'--':fmt(held)):'Keine g\u00fcltige A2-Leistung');\n"
" el('currentcoupler').textContent=data\?'Profil '+(profile\?\?'--')+' \u00b7 Referenz '+data.master+' \u00b7 '+(data.calibration_frequency_hz/1e6).toLocaleString('de-DE')+' MHz \u00b7 50 \u03a9':'A2-Messkopf: keine aktuellen Daten';\n"
" el('a2quality').textContent=!data\?'Keine Verbindung':valid\?'Vorl\u00e4ufige Kennlinie \u00b7 Messfrequenz nicht automatisch gepr\u00fcft':data.quality==='outside_calibrated_range'\?'A2 au\u00dferhalb der gemessenen Kennlinie \u00b7 kein g\u00fcltiger Leistungswert':'A2-Messung ung\u00fcltig oder \u00fcbersteuert';\n"
"}\n"
"\n"
"\n"
"async function poll(){const start=performance.now();try{\n"
" const r=await fetch('/api/v1/state',{cache:'no-store',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error();const x=await r.json();if(!x.current_coupler)throw Error();\n"
" drawA2Voltage(x.channels\?.find(c=>c.input==='A2-A3'));drawA2(x.current_coupler,x.curve_profiles\?.current);el('status').textContent='Verbunden';\n"
"}catch(e){drawA2Voltage(null);drawA2(null);el('status').textContent='Verbindung unterbrochen';}\n"
"setTimeout(poll,Math.max(20,200-(performance.now()-start)));}\n"
"el('a2reset').onclick=async()=>{try{const r=await fetch('/api/v1/peak/reset',{method:'POST',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error();if(lastA2)drawA2({...lastA2,peak_w:null},lastA2Profile);}catch(e){el('status').textContent='Hold-Reset fehlgeschlagen';}};\n"
"el('a2bar').ondblclick=()=>el('a2reset').click();\n"
"el('a2bar').title='Doppelklick: Hold zur\u00fccksetzen';\n"
"fetch('/api/v1/info').then(r=>r.json()).then(x=>el('version').textContent='Firmware '+x.version).catch(()=>{});poll();\n"
"</script></body></html>\n"
;
#endif
